services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    container_name: api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
